version: '2'
services:

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
    links:
     - redis
  web:
    image: nginx:1.11.1
    ports: 
      - "9080:80"
    depends_on: 
      - php
    volumes_from: 
      - php
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d
  redis:
    image: redis
    ports:
      - "6379:6379"